# Generated by Django 3.1.2 on 2020-10-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0005_auto_20201014_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='userImage',
        ),
    ]
