# Generated by Django 3.1.2 on 2020-10-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
