# Generated by Django 3.1.2 on 2020-10-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPage', '0010_following_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(blank=True, default='', max_length=100)),
                ('commentId', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('commentedBy', models.CharField(blank=True, default='', max_length=500)),
                ('commentedOf', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
