# Generated by Django 3.1.2 on 2020-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
