# Generated by Django 3.1.2 on 2020-10-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0012_post_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postId',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
